# Generated by Django 5.2.1 on 2025-05-15 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='language',
            field=models.CharField(default='en', help_text="Language code of the original comment (e.g. 'en', 'pl', 'sv').", max_length=10, verbose_name='Original Language'),
        ),
        migrations.AddField(
            model_name='comment',
            name='translated_comment',
            field=models.JSONField(blank=True, help_text="Dictionary with translated versions of the comment. Example: {'en': '...', 'de': '...'}", null=True, verbose_name='Translated Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Recipe'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
