# Generated by Django 5.0.3 on 2024-10-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_comments_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='categories',
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty_level',
            field=models.CharField(choices=[('EASY', 'Easy'), ('INTERMEDIATE', 'Intermediate'), ('DIFFICULT', 'Difficult')], default='Easy', max_length=100, verbose_name='Difficulty Level'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient_type',
            field=models.CharField(choices=[('VEGETABLE_BASED', 'Vegetable-Based'), ('MEAT_BASED', 'Meat-Based'), ('FISH_BASED', 'Fish-Based'), ('FRUIT_BASED', 'Fruit-Based'), ('SEAFOOD', 'Seafood'), ('DAIRY_BASED', 'Dairy-Based'), ('PASTA_RICE_BASED', 'Pasta/Rice-Based')], default='MEAT_BASED', max_length=100, verbose_name='Ingredient Type'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='preparation_method',
            field=models.CharField(choices=[('FRYING', 'Frying'), ('BOILING', 'Boiling'), ('GRILLING', 'Grilling'), ('BAKING', 'Baking'), ('STEAMING', 'Steaming'), ('SOUS-VIDE', 'Sous-vide'), ('RAW', 'Raw')], default='SOUS-VIDE', max_length=100, verbose_name='Preparation method'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='preparation_time',
            field=models.CharField(choices=[('QUICK', 'Quick'), ('MEDIUM', 'Medium'), ('TIME_CONSUMING', 'Time-Consuming')], default='Medium', max_length=100, verbose_name='Preparation time'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='type_of_dish',
            field=models.CharField(choices=[('APPETIZERS', 'Appetizers'), ('SOUPS', 'Soups'), ('SALADS', 'Salads'), ('MAIN_DISHES', 'Main Dishes'), ('DESSERTS', 'Desserts'), ('SNACKS', 'Snacks'), ('DRINKS', 'Drinks'), ('BREAD', 'Bread')], default='Main Dishes', max_length=100, verbose_name='Type of dish'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_color',
            field=models.CharField(default='#FFFFFF', max_length=10),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag_label',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag_type',
        ),
    ]
