# Generated by Django 5.1.3 on 2025-01-05 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_favoriterecipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookbook_name', models.CharField(blank=True, default='My CookBook', max_length=255, verbose_name='Cookbook name')),
                ('added_on', models.DateTimeField(auto_now_add=True, verbose_name='Added on')),
                ('notes', models.TextField(verbose_name='Notes')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['added_on'],
                'unique_together': {('user', 'recipe')},
            },
        ),
        migrations.DeleteModel(
            name='FavoriteRecipe',
        ),
    ]
