# Generated by Django 5.0.3 on 2024-10-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipe_categories_alter_tag_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag_name']},
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_color',
            field=models.CharField(default='#000000', max_length=10),
        ),
    ]
