# Generated by Django 5.1.3 on 2025-01-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_favoriterecipes_delete_favoriterecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriterecipes',
            name='notes',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Notes'),
        ),
    ]
