# Generated by Django 5.0.3 on 2024-11-08 18:48

import django.db.models.deletion
import recipes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipesteps'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_details', models.JSONField(validators=[recipes.models.validate_step_data], verbose_name='Step details')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipe')),
            ],
            options={
                'ordering': ['step_details__step_number'],
            },
        ),
        migrations.DeleteModel(
            name='RecipeSteps',
        ),
    ]
