# Generated by Django 5.1.3 on 2025-03-19 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('ratings_count', models.PositiveIntegerField(default=0, verbose_name='Ratings count')),
                ('average_rating', models.FloatField(default=0.0, verbose_name='Average rating')),
                ('favorite_count', models.PositiveIntegerField(default=0, verbose_name='Favorite count')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='Comment count')),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='recipes.recipe')),
            ],
        ),
    ]
