# Generated by Django 5.1.3 on 2025-03-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipestatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='comment_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Comment count'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='favorite_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Favorite count'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ratings_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Ratings count'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Views'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveIntegerField(verbose_name='Preparation time'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.PositiveIntegerField(verbose_name='Servings'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_time',
            field=models.PositiveIntegerField(verbose_name='Total time'),
        ),
        migrations.DeleteModel(
            name='RecipeStatistics',
        ),
    ]
