# Generated by Django 5.0.3 on 2024-11-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipestep_delete_recipesteps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipestep',
            options={'ordering': ['step_number']},
        ),
        migrations.AlterUniqueTogether(
            name='recipestep',
            unique_together={('recipe', 'step_number')},
        ),
        migrations.AddField(
            model_name='recipestep',
            name='instruction',
            field=models.TextField(default='Temporary instruction', verbose_name='Instruction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipestep',
            name='step_number',
            field=models.PositiveIntegerField(default='Default instruction', verbose_name='Step number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipestep',
            name='temperature',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperature'),
        ),
        migrations.AddField(
            model_name='recipestep',
            name='time',
            field=models.DurationField(blank=True, null=True, verbose_name='Time'),
        ),
        migrations.RemoveField(
            model_name='recipestep',
            name='step_details',
        ),
    ]
