# Generated by Django 5.1.3 on 2025-04-30 17:40

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_comment_count_recipe_favorite_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatableRecipe',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(parler.models.TranslatableModelMixin, 'recipes.recipe', models.Model),
        ),
        migrations.CreateModel(
            name='TranslatableRecipeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='recipes.translatablerecipe')),
            ],
            options={
                'verbose_name': 'translatable recipe Translation',
                'db_table': 'recipes_translatablerecipe_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
