# Generated by Django 5.1.3 on 2025-05-07 17:03

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_comment_count_recipe_favorite_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='description',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='name',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='preparation_steps',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tools',
        ),
        migrations.CreateModel(
            name='RecipeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, verbose_name='Name of recipe')),
                ('description', models.TextField(verbose_name='Description of recipe')),
                ('ingredients', models.TextField(verbose_name='Ingredients')),
                ('tools', models.TextField(verbose_name='Tools needed')),
                ('preparation_steps', models.TextField(verbose_name='Preparation steps')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'recipe Translation',
                'db_table': 'recipes_recipe_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
